config/routes.rb
Rails.application.routes.draw do
  resources :fuges
  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fuge.rb
class Fuge < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    content_security_policy do |p|
        p.script_src :self, 'nonce-12345abc'
    end
end

app/controllers/fuges_controller.rb
class FugesController < ApplicationController
  before_action :set_fuge, only: [:show, :edit, :update, :destroy]

  # GET /fuges
  # GET /fuges.json
  def index
    @fuges = Fuge.all
  end

  # GET /fuges/1
  # GET /fuges/1.json
  def show
  end

  # GET /fuges/new
  def new
    @fuge = Fuge.new
  end

  # GET /fuges/1/edit
  def edit
  end

  # POST /fuges
  # POST /fuges.json
  def create
    @fuge = Fuge.new(fuge_params)

    respond_to do |format|
      if @fuge.save
        format.html { redirect_to @fuge, notice: 'Fuge was successfully created.' }
        format.json { render :show, status: :created, location: @fuge }
      else
        format.html { render :new }
        format.json { render json: @fuge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuges/1
  # PATCH/PUT /fuges/1.json
  def update
    respond_to do |format|
      if @fuge.update(fuge_params)
        format.html { redirect_to @fuge, notice: 'Fuge was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuge }
      else
        format.html { render :edit }
        format.json { render json: @fuge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuges/1
  # DELETE /fuges/1.json
  def destroy
    @fuge.destroy
    respond_to do |format|
      format.html { redirect_to fuges_url, notice: 'Fuge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuge
      @fuge = Fuge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fuge_params
      params.require(:fuge).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fuges_helper.rb
module FugesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/fuges/_form.html.erb
<%= form_with(model: fuge) do |form| %>
  <% if fuge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fuge.errors.count, "error") %> prohibited this fuge from being saved:</h2>

      <ul>
        <% fuge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fuges/edit.html.erb
<h1>Editing Fuge</h1>

<%= render 'form', fuge: @fuge %>

<%= link_to 'Show', @fuge %> |
<%= link_to 'Back', fuges_path %>

app/views/fuges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fuges</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fuges.each do |fuge| %>
      <tr>
        <td><%= fuge.title %></td>
        <td><%= fuge.body %></td>
        <td><%= link_to 'Show', fuge %></td>
        <td><%= link_to 'Edit', edit_fuge_path(fuge) %></td>
        <td><%= link_to 'Destroy', fuge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuge', new_fuge_path %>
<%= javascript_include_tag 'hello' %>

app/views/fuges/new.html.erb
<h1>New Fuge</h1>

<%= render 'form', fuge: @fuge %>

<%= link_to 'Back', fuges_path %>

app/views/fuges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @fuge.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @fuge.body %>
</p>

<%= link_to 'Edit', edit_fuge_path(@fuge) %> |
<%= link_to 'Back', fuges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.body %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @todo.body %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>